/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package remotedesktop;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Admin
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrame frame = new JFrame("UltraViewer Form - Java Swing");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(450, 450);
        frame.setLayout(new BorderLayout(10, 10)); // Add padding around the frame content

        // Create a main panel to hold all components with BoxLayout (vertical alignment)
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15)); // Add padding around edges

        // Create a panel for user ID and password section
        JPanel userPanel = new JPanel(new GridLayout(2, 2, 10, 10)); // GridLayout with space between rows and columns
        userPanel.setBorder(BorderFactory.createTitledBorder("Cho phép điều khiển"));

        JLabel idLabel = new JLabel("ID của bạn:");
        JTextField idField = new JTextField(10);
        JLabel passLabel = new JLabel("Mật khẩu:");
        JPasswordField passField = new JPasswordField(10);

        userPanel.add(idLabel);
        userPanel.add(idField);
        userPanel.add(passLabel);
        userPanel.add(passField);

        mainPanel.add(userPanel);

        // Create a panel for partner ID and password section
        JPanel partnerPanel = new JPanel(new GridLayout(2, 2, 10, 10)); // Similar layout as above
        partnerPanel.setBorder(BorderFactory.createTitledBorder("Điều khiển máy tính khác"));

        JLabel partnerIdLabel = new JLabel("ID đối tác:");
        JTextField partnerIdField = new JTextField(10);
        JLabel partnerPassLabel = new JLabel("Mật khẩu:");
        JPasswordField partnerPassField = new JPasswordField(10);

        partnerPanel.add(partnerIdLabel);
        partnerPanel.add(partnerIdField);
        partnerPanel.add(partnerPassLabel);
        partnerPanel.add(partnerPassField);

        mainPanel.add(partnerPanel);

        // Create a panel for the checkboxes and buttons
        JPanel optionsPanel = new JPanel();
        optionsPanel.setLayout(new BoxLayout(optionsPanel, BoxLayout.Y_AXIS));
        optionsPanel.setBorder(BorderFactory.createTitledBorder("Truy cập mọi lúc"));
        optionsPanel.setAlignmentX(Component.LEFT_ALIGNMENT);

        JCheckBox autoRunCheckBox = new JCheckBox("Chạy UltraViewer cùng với Windows");
        JCheckBox preventSleepCheckBox = new JCheckBox("Ngăn không cho máy tính tự Sleep");
        JCheckBox remoteAccessCheckBox = new JCheckBox("Cho phép bật máy tính từ xa");

        optionsPanel.add(autoRunCheckBox);
        optionsPanel.add(preventSleepCheckBox);
        optionsPanel.add(remoteAccessCheckBox);

        mainPanel.add(optionsPanel);

        // Create the button panel for the start control button
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT)); // Align button to the right
        JButton startButton = new JButton("Bắt đầu điều khiển");
        buttonPanel.add(startButton);

        mainPanel.add(buttonPanel);

        // Add the main panel to the frame
        frame.add(mainPanel, BorderLayout.CENTER);

        // Make the frame visible
        frame.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
